### ISSUE TITLE
Embedding your lib into a WP plugin

### ISSUE THREAD

**Issue by crouti** [dannyvankooten/vat.php#16]
Hi, i embedded your lib in a plugin and it works perfectly, but one of my users gets the following error, which seem to be linked to your code:

```
[08-Apr-2018 13:05:09 UTC] PHP Fatal error:  Uncaught Error: Class 'SoapClient' not found in /var/www/html/illustration.tools/public_html/wp-content/plugins/rcp-vat/libs/vendor/dannyvankooten/vat.php/src/Vies/Client.php:63
Stack trace:
#0 /var/www/html/illustration.tools/public_html/wp-content/plugins/rcp-vat/libs/vendor/dannyvankooten/vat.php/src/Vies/Client.php(44): DvK\Vat\Vies\Client->getClient()
#1 /var/www/html/illustration.tools/public_html/wp-content/plugins/rcp-vat/libs/vendor/dannyvankooten/vat.php/src/Validator.php(93): DvK\Vat\Vies\Client->checkVat('39', '281928M')
#2 /var/www/html/illustration.tools/public_html/wp-content/plugins/rcp-vat/admin/class-rcp-vat-admin.php(666): DvK\Vat\Validator->validateExistence('39281928M')
#3 /var/www/html/illustration.tools/public_html/wp-content/plugins/rcp-vat/admin/class-rcp-vat-admin.php(724): Rcp_Vat_Admin->validateUserFields(Array, 'register')
#4 /var/www/html/illustration.tools/public_html/wp-includes/class-wp-hook.php(286): Rcp_Vat_Admin->rcp_vat_rcp_validate_user_fields_on_register(Array)
#5 /var/w in /var/www/html/illustration.tools/public_html/wp-content/plugins/rcp-vat/libs/vendor/dannyvankooten/vat.php/src/Vies/Client.php on line 63```

Any idea ?
Thanks

**Comment by bpolaszek** [comment]
It looks like their PHP configuration doesn't have `php-soap` extension installed.

**Comment by crouti** [comment]
Thanks a lot, and sorry for disturbing...
